export const SIGNATURE_BLANK = "iVBORw0KGgoAAAANSUhEUgAAAXYAAAH0CAYAAAApJga2AAAAAXNSR0IArs4c6QAAAARzQklUCAgI" +
    "CHwIZIgAAAb1SURBVHic7dTBCQAgEMAwdf+dzyUEoSQT9NU9M7MAyDi/AwB4y9gBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG" +
    "2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKM" +
    "HSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbY" +
    "AWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowd" +
    "IMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgB" +
    "YowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0g" +
    "xtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFi" +
    "jB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG" +
    "2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKM" +
    "HSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbY" +
    "AWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowd" +
    "IMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgB" +
    "YowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0g" +
    "xtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFi" +
    "jB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG" +
    "2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKM" +
    "HSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbY" +
    "AWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowd" +
    "IMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgB" +
    "YowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0g" +
    "xtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFi" +
    "jB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG2AFijB0gxtgBYowdIMbYAWKMHSDG" +
    "2AFijB0g5gKWrwfkckkAEAAAAABJRU5ErkJggg==";

export const CALENDAR = {
    monthNames: [
        'Enero',
        'Febrero',
        'Marzo',
        'Abril',
        'Mayo',
        'Junio',
        'Julio',
        'Agosto',
        'Septiembre',
        'Octubre',
        'Noviembre',
        'Diciembre'
    ],
    monthNamesShort: ['Ene.', 'Feb.', 'Mar.', 'Abr.', 'May.', 'Jun.', 'Jul.', 'Ago.', 'Sep.', 'Oct.', 'Nov.', 'Dic.'],
    dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    dayNamesShort: ['Dom.', 'Lun.', 'Mar.', 'Mie.', 'Jue.', 'Vie.', 'Sab.'],
    today: "Hoy"
}